[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "CHADA_kit"
description = "Python code for generating CHADA (CHAracterisation DAta) diagrams and tables using plantuml, with machine-readable, enhanced design based on bespoke CHADA themes."
authors = [
    {name = "Thomas G. Woodcock"},
]
maintainers = [{name = "Thomas G. Woodcock"},]
license = {file = "LICENSE"}

classifiers=[
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Development Status :: 3 - Alpha',
    'Environment :: X11 Applications :: Qt',
    'Intended Audience :: End Users/Desktop',
    'Intended Audience :: Science/Research',
    'License :: OSI Approved :: MIT License',
    'Operating System :: POSIX',
    'Operating System :: Microsoft :: Windows',
    'Topic :: Scientific/Engineering',
    'Topic :: Scientific/Engineering :: Visualization',
]
keywords = ["research", "data", "management", "visualization", "plantuml", "uml", "CHADA"]
requires-python = ">=3.6"
dependencies = [
]
dynamic = ["version"]

[project.readme]
'file' = "README.md"
'content-type' = "text/markdown"

[project.scripts]
CHADA_kit = "CHADA_kit.__init__:main"

[tool.setuptools.dynamic]
version = {attr = "CHADA_kit.__version__"}

[tool.setuptools.packages.find]
where = ["src"]
