''
'' Theme for MODA and CHADA diagrams, based on four colors from the plasma
'' colormap in matplotlib.
'' The colormap was evaluated at 0, 0.333, 0.667 and 1 to obtain the colours.
'' This is a perceptually uniform colormap which does not contain
'' both red and green colours and should therefore be suitable for
'' people who have difficulty distinguishing those colours
''
'' Author: Thomas G. Woodcock
''
'' Definition block:
''   here we define some variables for the style. These can easily be changed
''   programatically to generate many different themes, regardless of any
''   extra lines added to the style block below.
''   HyperlinkColor is currently hardwired to be the same as FontColor, but
''   this could easily be changed.
'' Start definition block
!$PUML_THEME = "MOCHADA-plasma"
!$THEME      = "MOCHADA-plasma"
!$OVERVIEW_BACKGROUNDCOLOR = Gray
!$OVERVIEW_FONTCOLOR = White
!$USER_CASE_BACKGROUNDCOLOR = "#0d0887"
!$USER_CASE_FONTCOLOR = White
!$EXPERIMENT_BACKGROUNDCOLOR = "#9c179e"
!$EXPERIMENT_FONTCOLOR = White
!$RAW_DATA_BACKGROUNDCOLOR = "#ed7953"
!$RAW_DATA_FONTCOLOR = White
!$DATA_PROCESSING_BACKGROUNDCOLOR = "#f0f921"
!$DATA_PROCESSING_FONTCOLOR = Black
!$USER_CASE_INPUT_BACKGROUNDCOLOR = "#0d0887"
!$USER_CASE_INPUT_FONTCOLOR = White
!$MODEL_BACKGROUNDCOLOR = "#9c179e"
!$MODEL_FONTCOLOR = White
!$RAW_OUTPUT_BACKGROUNDCOLOR = "#ed7953"
!$RAW_OUTPUT_FONTCOLOR = White
!$PROCESSED_OUTPUT_BACKGROUNDCOLOR = "#f0f921"
!$PROCESSED_OUTPUT_FONTCOLOR = Black
!$DATA_BASED_MODEL_BACKGROUNDCOLOR = "#f0f921-#9c179e"
!$DATA_BASED_MODEL_FONTCOLOR = White
!$FINAL_DATA_BACKGROUNDCOLOR = "#f0f921"
!$FINAL_DATA_FONTCOLOR = Black
!$FINAL_DATA_LINECOLOR = Blue
!$FINAL_DATA_LINETHICKNESS = "2.0"
!$USER_CASE_HYPERLINKCOLOR = $USER_CASE_FONTCOLOR
!$EXPERIMENT_HYPERLINKCOLOR = $EXPERIMENT_FONTCOLOR
!$RAW_DATA_HYPERLINKCOLOR = $DAW_DATA_FONTCOLOR
!$DATA_PROCESSING_HYPERLINKCOLOR = $DATA_PROCESSING_FONTCOLOR
!$USER_CASE_INPUT_HYPERLINKCOLOR = $USER_CASE_INPUT_FONTCOLOR
!$MODEL_HYPERLINKCOLOR = $MODEL_FONTCOLOR
!$RAW_OUTPUT_HYPERLINKCOLOR = $RAW_OUTPUT_FONTCOLOR
!$PROCESSED_OUTPUT_HYPERLINKCOLOR = $PROCESSED_OTUPUT_FONTCOLOR
!$DATA_BASED_MODEL_HYPERLINKCOLOR = $DATA_BASED_MODEL_FONTCOLOR
!$FINAL_DATA_HYPERLINKCOLOR = $FINAL_DATA_FONTCOLOR
''
skinparam defaultTextAlignment center
skinparam noteTextAlignment left
''
'' When mixing skinparam and <style>, it is very important to put <style> after skinparam
''
'' Style settings:
''   we give each of the 5 CHADA elements its own style and define styles
''   for groups containing one characterisation technique (group_single)
''   and several characterisation techniques (group_collection).
''   Each of the five MODA elements also gets it's own style. These are
''   similar to those of the CHADA elements but have different names,
''   allowing them to be distibguished. Two further groups are also
''   defined for groups of CHADA elements and groups of MODA elements.
''
<style>
jsonDiagram {
  MaximumWidth 600
}
.overview {
  BackgroundColor $OVERVIEW_BACKGROUNDCOLOR
  FontColor $OVERVIEW_FONTCOLOR
  HyperlinkColor $OVERVIEW_HYPERLINKCOLOR
}
.user_case {
  BackgroundColor $USER_CASE_BACKGROUNDCOLOR
  FontColor $USER_CASE_FONTCOLOR
  HyperlinkColor $USER_CASE_HYPERLINKCOLOR
}
.experiment {
  BackgroundColor $EXPERIMENT_BACKGROUNDCOLOR
  FontColor $EXPERIMENT_FONTCOLOR
  HyperlinkColor $EXPERIMENT_HYPERLINKCOLOR
}
.raw_data {
  BackgroundColor $RAW_DATA_BACKGROUNDCOLOR
  FontColor $RAW_DATA_FONTCOLOR
  HyperlinkColor $RAW_DATA_HYPERLINKCOLOR
}
.data_processing {
  BackgroundColor $DATA_PROCESSING_BACKGROUNDCOLOR
  FontColor $DATA_PROCESSING_FONTCOLOR
  HyperlinkColor $DATA_PROCESSING_HYPERLINKCOLOR
}
.final_data {
  BackgroundColor $FINAL_DATA_BACKGROUNDCOLOR
  FontColor $FINAL_DATA_FONTCOLOR
  HyperlinkColor $FINAL_DATA_HYPERLINKCOLOR
  LineColor $FINAL_DATA_LINECOLOR
  LineThickness $FINAL_DATA_LINETHICKNESS
}
.user_case_input {
  BackgroundColor $USER_CASE_INPUT_BACKGROUNDCOLOR
  FontColor $USER_CASE_INPUT_FONTCOLOR
  HyperlinkColor $USER_CASE_INPUT_HYPERLINKCOLOR
}
.model {
  BackgroundColor $MODEL_BACKGROUNDCOLOR
  FontColor $MODEL_FONTCOLOR
  HyperlinkColor $MODEL_HYPERLINKCOLOR
}
.raw_output {
  BackgroundColor $RAW_OUTPUT_BACKGROUNDCOLOR
  FontColor $RAW_OUTPUT_FONTCOLOR
  HyperlinkColor $RAW_OUTPUT_HYPERLINKCOLOR
}
.processed_output {
  BackgroundColor $PROCESSED_OUTPUT_BACKGROUNDCOLOR
  FontColor $PROCESSED_OUTPUT_FONTCOLOR
  HyperlinkColor $PROCESSED_OUTPUT_HYPERLINKCOLOR
}
.data_based_model {
  BackgroundColor $DATA_BASED_MODEL_BACKGROUNDCOLOR
  FontColor $DATA_BASED_MODEL_FONTCOLOR
  HyperlinkColor $DATA_BASED_MODEL_HYPERLINKCOLOR
}
.group_single {
  LineColor DodgerBlue
  FontColor DodgerBlue
  HyperlinkColor DodgerBlue
  RoundCorner 10
  BackgroundColor Beige
}
.group_collection {
  LineColor MediumBlue
  FontColor MediumBlue
  HyperlinkColor MediumBlue
  RoundCorner 10
  BackgroundColor Silver
}
.group_chada {
  LineColor Purple
  LineStyle 3
  FontColor Purple
  LineThickness 2
  HyperlinkColor Purple
  RoundCorner 10
  BackgroundColor White
}
.group_moda {
  LineColor Blue
  LineStyle 3
  FontColor Blue
  LineThickness 2
  HyperlinkColor Blue
  RoundCorner 10
  BackgroundColor White
}
note {
  FontColor Black
  LineColor Navy
  BackgroundColor WhiteSmoke
}
document {
   BackgroundColor White
}
</style>
