@startyaml
!theme MOCHADA-plasma_wide from ../../themes
#highlight "Overview" <<overview>>
#highlight "1. User Case" <<user_case>>
#highlight "2. Experiment" <<experiment>>
#highlight "3. Raw Data" <<raw_data>>
#highlight "4. Data Processing" <<data_processing>>
#highlight "Overview" / "Overview" <<overview>>
#highlight "1. User Case" / "1. User Case" <<user_case>>
#highlight "2. Experiment" / "2. Experiment" <<experiment>>
#highlight "3. Raw Data" / "3. Raw Data" <<raw_data>>
#highlight "4. Data Processing" / "4. Data Processing" <<data_processing>>
Overview:
  Overview: " "
  1. User Case: Bulk or thin film samples, usually electrically conducting. High vacuum, //P// ~ 10<sup>-6</sup> mbar
  2. Characterisation\nmethod: Electron Backscatter Diffraction (EBSD) in the Scanning Electron Microscope (SEM)
  3. Validation of\ncharacterisation: Measurement of crystallographic orientations, phase distributions, defects, etc.
  4. Access conditions\n(what is needed to\nrepeat the experiment): Sample preparation and experiment done in house. Post processing, open source.
1. User Case:
  1. User Case: " "
  1.1 User: Experienced user. High level of automation.
  1.2 Sample: Thin film or polished bulk material. Lateral dimensions typically ~ 1 cm
  1.3 Sample material\nproperties: Magnetic materials, Nd<sub>2</sub>Fe<sub>14</sub>B-based, or MnAl-C-based. Metallic. Microstructure":" grains, secondary phases, defects.
  1.4 Sampling process: Thin films":" promising samples cut from wafer containing varying compositions. Bulk samples cut from a cast or deformed material.
  1.5 Sample preparation: Thin films":" none. Bulk samples":" standard metallographic grinding and polishing.
  1.6 Hazards: None
  1.7 Characterisation\nenvironment: High vacuum, //P// ~ 10<sup>-6</sup> mbar, room temperature.
2. Experiment:
  2. Experiment: " "
  2.1 Probe/\nPhysics of Interaction: Electron beam. 20 kV accelerating voltage. Backscattered electrons are diffracted from lattice planes.
  2.2 Interaction Volume: Highly anisotropic shape due to 70° sample tilt angle, approximately 5 <U+03BC>m wide and 15 <U+03BC>m long (perpendicular to tilt axis)
  2.3 Calibration Process: Experimental geometry (working distance and detector distance) calibrated using single crystal Si sample, approx. yearly.
  2.4 Detector: Oxford Instruments CNano+ EBSD detector (phosphor screen with fibre optics).
  2.5 Signal: Backscattered and diffracted electrons are detected and a diffraction pattern is recorded for each beam position
  2.6 Measurement time: A few minutes to a few hours
  2.7 Measurement\nparameters: accelerating voltage, working distance, detector distance, tilt angle, beam current, detector resolution, static background pattern, dynamic background settings, Hough space resolution, band detection settings, phases selected, pattern saving options
3. Raw Data:
  3. Raw Data: " "
  3.1 Raw Data: Diffraction patterns: images of diffracted intensity on the detector. Orientation data: exported as h5oina (HDF5 format) containing all metadata, orientations as Euler angles, and optionally the original diffraction patterns.
  3.2 Unit: "EBSD patterns: lateral pixel size in <U+03BC>m, Euler angles in degrees or Radians"
  3.3 Data acquisition rate: Typically ~ 8 to ~ 400 patterns per second
4. Data Processing:
  4. Data Processing: " "
  4.1a Level of Expertise: Domain/High expertise. Equipment software (AZtec Crystal) can be used to generate many maps, pole figures etc, but the original patterns can also be analysed using the open source package 'Kikuchipy' for more advanced/detailed analysis.
  4.1b Data Normalisation: Some 'cleaning' of the data may be needed //e.g.// to remove single data points within a grain which spuriously contain a different orientation. Rotations can be applied to the orientations to obtain a more sensible reference orientation.
  4.2 Processing\nReproducibility: Indexing rate should be as high as possible, typically >> 90%. Steps are easily reproducible.
  4.3 Data Filtering\nProcesses: Static and dynamic background subtraction.
  4.4 Data Analysis\nProcedures: Hough transformation, identification of Hough peaks, matching with solutions from data describing the crystal structure of phases.
  4.5 Main Processed\nSignals: Diffraction patterns are processed giving Euler angles as a function of beam position
  4.6 Data Processing\nThrough Calibrations: Transformation from the detector coordinate system to the crystal coordinate system is done via the detector orientation, which is obtained from calibration.
  4.7a Properties\n(Elaborated Data): Euler angles are analysed giving measures of texture //e.g.// pole figures, pole plots, FWHM of a pole plot.
  4.7b Quality of the Data: Mean Angular Deviation gives the goodness of fit between pattern and simulation at each pixel. Number of Bands shows how many bands were indexed at each pixel. Indexing rate shows how many patterns were indexed overall.
  4.8 Data Management: Data in HDF5 format (h5oina) will be uploaded to a repository for future use.
@endyaml
