@startuml
label l1 [
{{
!theme MOCHADA-CWA from ../../themes
title MOCHADA-CWA
:User Case; <<user_case>>
:Experiment; <<experiment>>
:Raw Data; <<raw_data>>
:Data Processing; <<data_processing>>
:Final Data; <<final_data>>
}}
]
label l2 [
{{
!theme MOCHADA-bwr from ../../themes
title MOCHADA-bwr
:User Case; <<user_case>>
:Experiment; <<experiment>>
:Raw Data; <<raw_data>>
:Data Processing; <<data_processing>>
:Final Data; <<final_data>>
}}
]
label l3 [
{{
!theme MOCHADA-bwr_5 from ../../themes
title MOCHADA-bwr_5
:User Case; <<user_case>>
:Experiment; <<experiment>>
:Raw Data; <<raw_data>>
:Data Processing; <<data_processing>>
:Final Data; <<final_data>>
}}
]
label l4 [
{{
!theme MOCHADA-cividis from ../../themes
title MOCHADA-cividis
:User Case; <<user_case>>
:Experiment; <<experiment>>
:Raw Data; <<raw_data>>
:Data Processing; <<data_processing>>
:Final Data; <<final_data>>
}}
]
label l5 [
{{
!theme MOCHADA-cividis_5 from ../../themes
title MOCHADA-cividis_5
:User Case; <<user_case>>
:Experiment; <<experiment>>
:Raw Data; <<raw_data>>
:Data Processing; <<data_processing>>
:Final Data; <<final_data>>
}}
]
label l6 [
{{
!theme MOCHADA-coolwarm from ../../themes
title MOCHADA-coolwarm
:User Case; <<user_case>>
:Experiment; <<experiment>>
:Raw Data; <<raw_data>>
:Data Processing; <<data_processing>>
:Final Data; <<final_data>>
}}
]
label l7 [
{{
!theme MOCHADA-coolwarm_5 from ../../themes
title MOCHADA-coolwarm_5
:User Case; <<user_case>>
:Experiment; <<experiment>>
:Raw Data; <<raw_data>>
:Data Processing; <<data_processing>>
:Final Data; <<final_data>>
}}
]
label l8 [
{{
!theme MOCHADA-jet from ../../themes
title MOCHADA-jet
:User Case; <<user_case>>
:Experiment; <<experiment>>
:Raw Data; <<raw_data>>
:Data Processing; <<data_processing>>
:Final Data; <<final_data>>
}}
]
label l9 [
{{
!theme MOCHADA-jet_5 from ../../themes
title MOCHADA-jet_5
:User Case; <<user_case>>
:Experiment; <<experiment>>
:Raw Data; <<raw_data>>
:Data Processing; <<data_processing>>
:Final Data; <<final_data>>
}}
]
label l10 [
{{
!theme MOCHADA-PiYG from ../../themes
title MOCHADA-PiYG
:User Case; <<user_case>>
:Experiment; <<experiment>>
:Raw Data; <<raw_data>>
:Data Processing; <<data_processing>>
:Final Data; <<final_data>>
}}
]
label l11 [
{{
!theme MOCHADA-PiYG_5 from ../../themes
title MOCHADA-PiYG_5
:User Case; <<user_case>>
:Experiment; <<experiment>>
:Raw Data; <<raw_data>>
:Data Processing; <<data_processing>>
:Final Data; <<final_data>>
}}
]
label l12 [
{{
!theme MOCHADA-plasma from ../../themes
title MOCHADA-plasma
:User Case; <<user_case>>
:Experiment; <<experiment>>
:Raw Data; <<raw_data>>
:Data Processing; <<data_processing>>
:Final Data; <<final_data>>
}}
]
label l13 [
{{
!theme MOCHADA-plasma_5 from ../../themes
title MOCHADA-plasma_5
:User Case; <<user_case>>
:Experiment; <<experiment>>
:Raw Data; <<raw_data>>
:Data Processing; <<data_processing>>
:Final Data; <<final_data>>
}}
]
label l14 [
{{
!theme MOCHADA-rainbow from ../../themes
title MOCHADA-rainbow
:User Case; <<user_case>>
:Experiment; <<experiment>>
:Raw Data; <<raw_data>>
:Data Processing; <<data_processing>>
:Final Data; <<final_data>>
}}
]
label l15 [
{{
!theme MOCHADA-rainbow_5 from ../../themes
title MOCHADA-rainbow_5
:User Case; <<user_case>>
:Experiment; <<experiment>>
:Raw Data; <<raw_data>>
:Data Processing; <<data_processing>>
:Final Data; <<final_data>>
}}
]
label l16 [
{{
!theme MOCHADA-RdBu from ../../themes
title MOCHADA-RdBu
:User Case; <<user_case>>
:Experiment; <<experiment>>
:Raw Data; <<raw_data>>
:Data Processing; <<data_processing>>
:Final Data; <<final_data>>
}}
]
label l17 [
{{
!theme MOCHADA-RdBu_5 from ../../themes
title MOCHADA-RdBu_5
:User Case; <<user_case>>
:Experiment; <<experiment>>
:Raw Data; <<raw_data>>
:Data Processing; <<data_processing>>
:Final Data; <<final_data>>
}}
]
label l18 [
{{
!theme MOCHADA-seismic from ../../themes
title MOCHADA-seismic
:User Case; <<user_case>>
:Experiment; <<experiment>>
:Raw Data; <<raw_data>>
:Data Processing; <<data_processing>>
:Final Data; <<final_data>>
}}
]
label l19 [
{{
!theme MOCHADA-seismic_5 from ../../themes
title MOCHADA-seismic_5
:User Case; <<user_case>>
:Experiment; <<experiment>>
:Raw Data; <<raw_data>>
:Data Processing; <<data_processing>>
:Final Data; <<final_data>>
}}
]
label l20 [
{{
!theme MOCHADA-Set1 from ../../themes
title MOCHADA-Set1
:User Case; <<user_case>>
:Experiment; <<experiment>>
:Raw Data; <<raw_data>>
:Data Processing; <<data_processing>>
:Final Data; <<final_data>>
}}
]
label l21 [
{{
!theme MOCHADA-Set1_5 from ../../themes
title MOCHADA-Set1_5
:User Case; <<user_case>>
:Experiment; <<experiment>>
:Raw Data; <<raw_data>>
:Data Processing; <<data_processing>>
:Final Data; <<final_data>>
}}
]
label l22 [
{{
!theme MOCHADA-Set2 from ../../themes
title MOCHADA-Set2
:User Case; <<user_case>>
:Experiment; <<experiment>>
:Raw Data; <<raw_data>>
:Data Processing; <<data_processing>>
:Final Data; <<final_data>>
}}
]
label l23 [
{{
!theme MOCHADA-Set2_5 from ../../themes
title MOCHADA-Set2_5
:User Case; <<user_case>>
:Experiment; <<experiment>>
:Raw Data; <<raw_data>>
:Data Processing; <<data_processing>>
:Final Data; <<final_data>>
}}
]
label l24 [
{{
!theme MOCHADA-viridis from ../../themes
title MOCHADA-viridis
:User Case; <<user_case>>
:Experiment; <<experiment>>
:Raw Data; <<raw_data>>
:Data Processing; <<data_processing>>
:Final Data; <<final_data>>
}}
]
label l25 [
{{
!theme MOCHADA-viridis_5 from ../../themes
title MOCHADA-viridis_5
:User Case; <<user_case>>
:Experiment; <<experiment>>
:Raw Data; <<raw_data>>
:Data Processing; <<data_processing>>
:Final Data; <<final_data>>
}}
]
@enduml
